### ISSUE TITLE
rostopic list is missing

### ISSUE THREAD

**Issue by ipekbocegi** [hansonrobotics/pi_vision#18]
First of all, thanks for sharing pi_vision

I followed the master branch and installed all steps accordingly. I use Ubuntu 14.04, OpenCV 3.0.0 beta, and ROS 1.11.10 - Indigo on Asus X555LN laptop. I am newbie on python, ubuntu and ROS.

When I write "roslaunch ros2opencv usb_cam.launch " in terminal, it runs properly without any error. But when I write "rostopic list" it does not show neither faces/face_locations nor faceEvent/face_event. Instead it shows:

/camera/camera_info
/camera/image_raw
/camera/image_raw/compressed
/camera/image_raw/compressed/parameter_descriptions
/camera/image_raw/compressed/parameter_updates
/camera/image_raw/compressedDepth
/camera/image_raw/compressedDepth/parameter_descriptions
/camera/image_raw/compressedDepth/parameter_updates
/camera/image_raw/theora
/camera/image_raw/theora/parameter_descriptions
/camera/image_raw/theora/parameter_updates
/rosout
/rosout_agg

Besides I can not see any camera output via rviz using these topics..

What should I do now? Why I am not able to see face and faceEvent?

Any help would be appreciated. Thanks

**Comment by vytasrgl** [comment]
`roslaunch pi_face_tracker face_tracker_usb_cam.launch` should help.

**Comment by ipekbocegi** [comment]
Thanks but it gives me this error:

Traceback (most recent call last):
File "/home/milvus/catkin_ws/src/pi_vision/pi_face_tracker/nodes/face_tracker.py", line 40, in
from ros2opencv import ROS2OpenCV
File "/home/milvus/catkin_ws/devel/lib/python2.7/dist-packages/ros2opencv/init.py", line 34, in
exec(__fh.read())
File "", line 37, in
File "/usr/lib/python2.7/dist-packages/cv.py", line 1, in
from cv2.cv import *
ImportError: No module named cv

**Comment by ipekbocegi** [comment]
ok but that gives me this error:

Traceback (most recent call last):
File "/home/milvus/catkin_ws/src/pi_vision/pi_face_tracker/nodes/face_tracker.py", line 40, in
from ros2opencv import ROS2OpenCV
File "/home/milvus/catkin_ws/devel/lib/python2.7/dist-packages/ros2opencv/init.py", line 34, in
exec(__fh.read())
File "", line 37, in
File "/usr/lib/python2.7/dist-packages/cv.py", line 1, in
from cv2.cv import *
ImportError: No module named cv

**Comment by Gaboose** [comment]
Might be because you're using OpenCV 3 Beta. To install the last stable release OpenCV 2.4, run `apt-get install python-opencv`.

**Comment by ipekbocegi** [comment]
True guiding. Thank you.

First I tried "apt-get install python-opencv" It says it is already newest version.
Then I deleted OpenCV 3 beta and installed OpenCV 2.4.9 and now pi_face_tracker is working. It gives me :

[INFO] [WallTime: 1427723919.187711] Starting pi_face_tracker
[INFO] [WallTime: 1427723919.331327] {1: <Face no.1 @ (192, 218, 224, 224) - 0.99 - new>}

Now I see following topics:
/camera/camera_info
/camera/face_event
/camera/face_locations
/camera/image_raw
/camera/image_raw/compressedDepth
/camera/image_raw/compressedDepth/parameter_descriptions
/camera/image_raw/compressedDepth/parameter_updates
/camera/pi_face_tracker/image
/input_depth_image
/rosout
/rosout_agg

I lost these I don't know why:
/camera/image_raw/compressed
/camera/image_raw/compressed/parameter_descriptions
/camera/image_raw/compressed/parameter_updates
/camera/image_raw/theora
/camera/image_raw/theora/parameter_descriptions
/camera/image_raw/theora/parameter_updates
